<?php
/**
 * Email template for submission confirmation
 * Available variables: $data array with all form data
 */
?>
<html>
<head>
    <title>Hong Kong Occupational Therapy Conference 2025 - Abstract Submission Confirmation</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #f8f9fa; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .details { background-color: #f8f9fa; padding: 15px; margin: 15px 0; }
        .section { margin: 20px 0; }
        h2 { color: #0073aa; }
        h3 { color: #333; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        h4 { color: #555; margin-top: 15px; }
        ul { padding-left: 20px; }
        li { margin: 5px 0; }
    </style>
</head>
<body>
    <div class="content">
        <p><strong>Subject: Hong Kong Occupational Therapy Conference 2025 - Abstract Submission Confirmation</strong></p>
        
        <p>Dear <?php echo esc_html($data['title'] . ' ' . $data['surname'] . ', ' . $data['given_name']); ?>,</p>
        
        <p>Thank you for submitting your abstract titled "<?php echo esc_html($data['abstract_title']); ?>" to the Hong Kong Occupational Therapy Conference 2025. We are pleased to confirm that your submission has been received successfully.</p>
        
        <p>Your abstract is currently undergoing a review process, and you will be notified of the outcome by 27th October 2025. We appreciate your patience during this time. You can log in to the abstract submission system to submit or modify your abstract(s) before 27th September 2025 00:00. The link is: <?php echo home_url('/abstract-submission/'); ?></p>
        
        <p>This email is automatically generated by the system. Please do not reply.</p>
        
        <p>Should you have any inquiries regarding the event, please feel free to contact Ms. Lydia Yip by email (conference@hkota.org.hk).</p>
        
        <p>Thank you for your contribution, and we look forward to the possibility of including your work in our program.</p>
        
        <div class="section">
            <h3>Abstract Details</h3>
            <div class="details">
                <ul>
                    <li><strong>Title:</strong> <?php echo esc_html($data['abstract_title']); ?></li>
                    <li><strong>Author:</strong> <?php echo esc_html($data['title'] . ' ' . $data['surname'] . ', ' . $data['given_name']); ?></li>
                    <li><strong>Contact Email:</strong> <?php echo esc_html($data['contact_email']); ?></li>
                    <li><strong>Organization:</strong> <?php echo esc_html($data['organization']); ?></li>
                    <li><strong>Theme:</strong> <?php echo esc_html($data['theme']); ?></li>
                    <li><strong>Presentation Preference:</strong> <?php echo esc_html($data['presentation_preference']); ?></li>
                    <li><strong>Submission Date:</strong> <?php echo current_time('Y-m-d H:i:s'); ?></li>
                </ul>
            </div>
        </div>
        
        <p>Best regards,<br>
        Scientific Committee<br>
        Hong Kong Occupational Therapy Conference 2025</p>
    </div>
</body>
</html>
